### ISSUE TITLE
[Feature request] Per-website delay

### ISSUE THREAD

**Issue by KaKi87** [Claxtastic/just-refresh#1]
Thanks

**Comment by Claxtastic** [comment]
Good idea! I just released an update that should have what you're looking for:

https://chrome.google.com/webstore/detail/just-refresh/pgaimkehoiabhliejchbnamlboniofpd?hl=en

**Comment by KaKi87** [comment]
Would it be possible to :
- set the per-website delay directly from a modal window (without going to the extension settings)
- make it work on the whole domain (applying same delay on any reddit.com page for example)

Thanks
