### ISSUE TITLE
[Feature request] Pattern matching

### ISSUE THREAD

**Issue by tysonclugg** [Claxtastic/just-refresh#3]
Currently, the per-site settings [appear to be URL specific](https://github.com/Claxtastic/just-refresh/blob/d2a490cca1bdd9f213dd6f86ff9c40885a2f5774/background.js#L46-L47).  It would be nice to allow pattern matching via one or more patterns.  My use-case is a mission-control type web app that changes URL, but periodically fails and needs a page refresh to reset the page state.

I'd be happy with any one (or all!) of the following match patterns being applied when the relevant option is applied in the relevant per-site settings (a select box/radio if multiple pattern types, or a simple checkbox if only one):

- URL prefix: `https://www.mysite.com/`
- URL glob: `https://www.mysite.com/foo/*`
- URL RegEx: `^https://www\.mysite\.com/foo/`
- Domain match: `mysite.com` (should match `www.mysite.com`, `mysite.com`, etc).
- Domain RegEx: `^(.*\.)mysite\.com$`
- Domain glob: `*.mysite.com` (should also match `mysite.com`).

If you're OK with any of the above, I'm happy to create a PR as per your preferences.

PS: Thanks for the great extension!

**Comment by Claxtastic** [comment]
Hello,

I received another issue regarding URL matching too, I considered it when I initially updated for site specific settings also. I think that the pattern that makes most sense, i.e. most useful, easiest to implement, and understand would be domain matching. So I've went and added that, I'll release to the Chrome Web Store soon.

Here's how it works:
![image](https://user-images.githubusercontent.com/11482471/110172695-23580d80-7dc3-11eb-9f8e-eed402cf37a1.png)

There's simply a new checkbox on the per-URL settings table for whether or not to match any URL from the given domain, defaults to false. If you check the box and submit a URL like https://twitter.com/home, it will trim it and save twitter.com for simplicity/readability. 

As per above example, if I have a tab with URL https://twitter.com/home and I click the extension, the tab will refresh every 3 minutes.

If I have another tab with URL https://twitter.com/explore, or https://twitter.com/bookmarks, (anything but https://twitter.com/home), the tab will refresh every 2 minutes.

So I think that provides some flexibility while remaining simple in the code, and in the settings.

Although I guess the most extensible and "advanced user" option would be to just add another field, say "Pattern match: " where you could paste in a regex to match. Maybe that can be added as well 🙂
